### PR TITLE
Apply .editorconfig rules and consistent code formatting

### PR DESCRIPTION
**Pull request by anselmh**
This sets a common format for the codebase, [following the .editorconfig](https://github.com/w3c/mailing-list-archives/pull/6) file in the linked Pull Request.

This PR is almost entirely only reformatting (indentation, tabs->spaces, missing semicolons, various CSS styles).

### CODE REVIEW

**Comment by ZoeBijl** [comment]
:+1:

**Comment by gosko** [comment]
Thanks for the contribution but I don't think we should worry about these kinds of details for now. Much of this old code will simply be obsoleted once we come up with something new.

**Comment by anselmh** [comment]
Thanks @gosko for the feedback. To avoid this in future (people called for participation here on twitter) it would make sense to _not_ include obsolete code at all if you don’t want it to be modified. But if the code will still be around for some time it’s better to have it in a proper way than in the current.

**Comment by anselmh** [comment]
That said, if you don’t think this PR fits into the repo here, please feel free to close it. No strong feelings, just a proposal. ;)

**Comment by ZoeBijl** [comment]
I think it's never the less good to have an editor config file; it will ensure new code is consistent. It might not be all that important in this stage, but couldn't hurt either.

**Comment by tripu** [comment]
Better formatting is always good, and I agree that this codebase could benefit from some normalisation. Thank you!

My only concern with this one, and with #6, is that all that reformatting will obscure the &ldquo;actual&rdquo; changes we want to make in these pages: when we're ready to deploy the new UI, the diff will be very long and it will be difficult to tell apart meaningful changes from code styling.

Shouldn't we leave styling the code for after we're done working on the pages&hellip;?

Again, I think `.editorconfig` is a great addition, and I'll try to extend that approach to other projects!

(Assigning this one and #6 to @gosko to give him the last word here.)

> This PR is almost entirely only reformatting

@anselmh, what is _not_ reformatting in your commits? I'm just curious about substantive changes we should be aware of&hellip;

**Comment by anselmh** [comment]
This PR is only targeting code formatting. It also makes the CSS selectors and values consistent which is not part of editorconfig but there are no other substantial changes in here.

**Comment by ZoeBijl** [comment]
@tripu 

> Shouldn't we leave styling the code for after we're done working on the pages…?

I understand your concerns. I'm not familiar with which document types this would be an issue for (I'm guessing the HTML?), but we could activate this for something like the CSS only (which I don't think would be an issue).

**Comment by anselmh** [comment]
Sorry, I don’t know anything about the consequences of merging this. I can only see what is in this repository which should not be a problem at all. I _assume_ it’s about all the messages’ content that is stored somewhere else. In that case, it might make sense to write a bot for this?

The reason why I opened this PR is to make it more attractive for people to participate/contribute. With the current—sorry about this—messy code formatting, I wouldn’t contribute myself so I wanted to fix that first.

**Comment by anselmh** [comment]
I just thought if it would be a good idea to add some notes on relations/implications/dependencies that this repository has besides what people like me can see in the repo itself? It might help to understand certain decisions here.

**Comment by gosko** [comment]
Hi guys, I updated the project overview page to try to make it clearer what kind of contributions would be most useful at this stage. Feedback welcome!

I am going to close these PRs -- I appreciate the contribution but I feel that this kind of thing is more important when you have dozens of developers actively working on a common code base. Right now I am really just looking for design ideas and will be happy to accept proposals in any format; if we start to gravitate towards a specific design we can make sure it has clean markup before deploying it.

**Pull request closed without merging**
